spring.profiles.default: local

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/waffle_account?useUnicode=true&characterEncoding=utf8
    username: wath
    password: teamsso

---

spring.config.activate.on-profile: dev

secret-names: dev/waffle-account

spring:
  r2dbc:
    url:
    username:
    password:
