spring.profiles.default: dev

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 760558146658-s29dkmip6ktv4msbnlodqq61rdlm8qtu.apps.googleusercontent.com
            client-secret: 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
  r2dbc:
    url: r2dbc:mysql://localhost:3306/waffle_account?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: wath
    password: teamsso

auth:
  jwt:
    issuer: https://account-api-local.wafflestudio.com
    access:
      privateKey: Kd47YhrOhGFy4HPljfCIJ9jzaFmSwylY
    refresh:
      privateKey: tRiGb4Brml6ytdcoRgOqV35Rh8bKgX9k

---

spring.config.activate.on-profile: dev

secret-names: dev/waffle-account

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 760558146658-s29dkmip6ktv4msbnlodqq61rdlm8qtu.apps.googleusercontent.com
            client-secret: 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
  r2dbc:
    url:
    username:
    password:
auth:
  jwt:
    issuer: https://account-api-dev.wafflestudio.com
    access:
      privateKey:
    refresh:
      privateKey:
