spring.profiles.default: dev

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/waffle_account?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: wath
    password: teamsso
auth:
  jwt:
    issuer: https://account-api-local.wafflestudio.com
    privateKey: WhgckdYsDHVopvL2ID6QIDs0PqGpD3DB

---

spring.config.activate.on-profile: dev

secret-names: dev/waffle-account

spring:
  r2dbc:
    url:
    username:
    password:
auth:
  jwt:
    issuer: https://account-api-dev.wafflestudio.com
    privateKey:
