=== PUT /v1/auth/signin

==== Request
[horizontal]
Body:: email, password

==== Response
[horizontal]
Body:: access_token, refresh_token

==== Examples
.200 OK
[%collapsible]
====
operation::signin-200[snippets='curl-request,http-request,http-response']
====
.400 Bad Request
[%collapsible]
====
operation::signin-400[snippets='curl-request,http-request,http-response']
====
.401 Unauthorized
[%collapsible]
====
operation::signin-401[snippets='curl-request,http-request,http-response']
====
.403 Forbidden
[%collapsible]
====
operation::signin-403[snippets='curl-request,http-request,http-response']
====
.404 Not Found
[%collapsible]
====
operation::signin-404[snippets='curl-request,http-request,http-response']
====

=== POST /v1/oauth/{provider}

==== Request

==== Response

==== Examples

=== PUT /v1/validate

==== Request
[horizontal]
Header:: userId

==== Response
[horizontal]
Body:: user_id

==== Examples
.200 OK
[%collapsible]
====
operation::validate-200[snippets='curl-request,http-request,http-response']
====
.400 Bad Request
[%collapsible]
====
operation::validate-400[snippets='curl-request,http-request,http-response']
====

=== PUT /v1/refresh

==== Request
[horizontal]
Body:: refresh_token

==== Response
[horizontal]
Body:: access_token

==== Examples
.200 OK
[%collapsible]
====
operation::refresh-200[snippets='curl-request,http-request,http-response']
====
.400 Bad Request
[%collapsible]
====
operation::refresh-400[snippets='curl-request,http-request,http-response']
====
.401 Unauthorized
[%collapsible]
====
operation::refresh-401[snippets='curl-request,http-request,http-response']
====
.403 Forbidden
[%collapsible]
====
operation::refresh-403[snippets='curl-request,http-request,http-response']
====
