=== PUT /v1/auth/signin

OAuth가 아닌, 이메일과 비밀번호로 로그인하는 API입니다.

==== Request

operation::signin-200[snippets='request-fields']

==== Response

다음은 가능한 HTTP 응답 코드와 각각의 의미를 나타냅니다.

|===
|HTTP Status Code |Description
|200 OK |로그인이 정상적으로 완료되었습니다.
|400 Bad Request |요청의 형식이 잘못되었습니다.
|401 Unauthorized |잘못된 비밀번호입니다.
|403 Forbidden |탈퇴 등의 사유로 비활성 상태인 사용자입니다.
|404 Not Found |존재하지 않는 사용자입니다.
|===

다음은 응답이 `200 OK` 일 때 API가 반환하는 값들입니다.

operation::signin-200[snippets='response-fields']

==== Examples
.200 OK
[%collapsible]
====
operation::signin-200[snippets='curl-request,http-request,http-response']
====
.400 Bad Request
[%collapsible]
====
operation::signin-400[snippets='curl-request,http-request,http-response']
====
.401 Unauthorized
[%collapsible]
====
operation::signin-401[snippets='curl-request,http-request,http-response']
====
.403 Forbidden
[%collapsible]
====
operation::signin-403[snippets='curl-request,http-request,http-response']
====
.404 Not Found
[%collapsible]
====
operation::signin-404[snippets='curl-request,http-request,http-response']
====

=== POST /v1/oauth/{provider}

TBD

==== Request

==== Response

==== Examples

=== PUT /v1/validate

==== Request

operation::validate-200[snippets='request-headers']

==== Response

다음은 가능한 HTTP 응답 코드와 각각의 의미를 나타냅니다.

|===
|HTTP Status Code |Description
|200 OK |요청이 정상적으로 처리되었습니다.
|400 Bad Request |요청의 형식이 잘못되었습니다.
|===

다음은 응답이 `200 OK` 일 때 API가 반환하는 값들입니다.

operation::validate-200[snippets='response-fields']

==== Examples
.200 OK
[%collapsible]
====
operation::validate-200[snippets='curl-request,http-request,http-response']
====
.400 Bad Request
[%collapsible]
====
operation::validate-400[snippets='curl-request,http-request,http-response']
====

=== PUT /v1/refresh

==== Request

operation::refresh-200[snippets='request-fields']

==== Response

다음은 가능한 HTTP 응답 코드와 각각의 의미를 나타냅니다.

|===
|HTTP Status Code |Description
|200 OK |새로운 access token 발급이 정상적으로 완료되었습니다.
|400 Bad Request |요청의 형식이 잘못되었습니다.
|401 Unauthorized |잘못된 refresh token입니다.
|403 Forbidden |탈퇴 등의 사유로 비활성 상태인 사용자입니다.
|===

다음은 응답이 `200 OK` 일 때 API가 반환하는 값들입니다.

operation::refresh-200[snippets='response-fields']

==== Examples
.200 OK
[%collapsible]
====
operation::refresh-200[snippets='curl-request,http-request,http-response']
====
.400 Bad Request
[%collapsible]
====
operation::refresh-400[snippets='curl-request,http-request,http-response']
====
.401 Unauthorized
[%collapsible]
====
operation::refresh-401[snippets='curl-request,http-request,http-response']
====
.403 Forbidden
[%collapsible]
====
operation::refresh-403[snippets='curl-request,http-request,http-response']
====
