name: Deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest-dev
      BUILD_NUMBER: ${{ github.run_number }}
      ECR_REGISTRY: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com
      ECR_REPOSITORY: sso/waffle-account-server
      S3_BUCKET_NAME: waffle-account-server-build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload Dockerrun.aws.json to S3
        run: |
          mv Dockerrun-dev.aws.json Dockerrun.aws.json
          zip deploy-dev.zip Dockerrun.aws.json
          aws s3 cp deploy-dev.zip s3://$S3_BUCKET_NAME/deploy-dev.zip

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker Build, tag, and push image to ECR
        id: build-image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Delete untagged images in ECR
        run: |
          UNTAGGED_IMAGES=$( aws ecr list-images --repository-name $ECR_REPOSITORY --filter "tagStatus=UNTAGGED" --query 'imageIds[*]' --output json )
          aws ecr batch-delete-image --repository-name $ECR_REPOSITORY --image-ids "$UNTAGGED_IMAGES" || true

      - name: Deploy to ElasticBeanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name waffle-account-server \
            --version-label dev-$BUILD_NUMBER \
            --description dev-$BUILD_NUMBER \
            --source-bundle S3Bucket=$S3_BUCKET_NAME,S3Key='deploy-dev.zip'
          aws elasticbeanstalk update-environment \
            --environment-name waffle-account-server-dev \
            --version-label dev-$BUILD_NUMBER

      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.1.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: team-sso
          SLACK_TITLE: NEW RELEASE
          SLACK_USERNAME: waffle-account-server-dev
          SLACK_ICON: https://user-images.githubusercontent.com/35535636/158051666-322decf3-c7d9-414d-a9bd-ec172054ab96.png
          SLACK_MESSAGE: Check <https://ap-northeast-2.console.aws.amazon.com/elasticbeanstalk/home?region=ap-northeast-2#/environment/dashboard?applicationName=waffle-account-server&environmentId=e-pcafnzntsp|EB> for updated environment
          SLACK_FOOTER: http://account-api-dev.wafflestudio.com
