name: Test CI

on:
    push:
        branches: [ develop, main ]
    pull_request:
        branches: [ develop, main ]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-northeast-2

            - name: Initiate Database
              run: |
                  mysql -uroot -h127.0.0.1 -proot -e "CREATE USER 'wath'@'%' IDENTIFIED BY 'teamsso'"
                  mysql -uroot -h127.0.0.1 -proot -e "CREATE DATABASE waffle_account"
                  mysql -uroot -h127.0.0.1 -proot -e "GRANT ALL PRIVILEGES ON waffle_account.* TO 'waffle_account'@'%'"

            - name: Run Tests
              run: |
                  ./gradlew clean test
